### ISSUE TITLE
Enable GPU Support

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1051]
We need to enable GPU support in the Mesos framework so Scale will receive resource offers from GPU nodes.

**Comment by dfaller** [comment]
We're punting on this for now.

**Comment by nevasway** [comment]
What's the timeframe for adding GPU support? I see that this list https://github.com/ngageoint/scale/wiki/Priority-List has *Mesos universal containerizer (first-class GPU support)* listed as a *Priority 2* but I'd like to know what that means in terms of time. Will we have to wait weeks? months? years?

**Comment by dfaller** [comment]
It can be tough to estimate long term since our project tends to have shifting priorities, but as of right now I'd estimate that first-class GPU support is around 6 to 8 months away.

Note that this doesn't mean you can't run jobs that use GPUs, you will just have to work around some limitations, such as only being able to run one GPU job per node at a time (since Mesos isn't scheduling which GPUs are available to your job, your job just assumes it has use of all GPUs on the node). You will also have to set up your job and nodes with the correct CUDA libraries, see [https://github.com/ngageoint/scale/wiki/Adding-NVIDIA-CUDA-support-to-your-Mesos-Docker-Containerizer](https://github.com/ngageoint/scale/wiki/Adding-NVIDIA-CUDA-support-to-your-Mesos-Docker-Containerizer)

**Comment by nevasway** [comment]
I'm interested in learning more about that "second class" option for running GPU jobs with Scale.

I have two agent nodes with GPUs but those nodes aren't listed on my Scale web interface 
`http://<MasterIP>/service/scale/#/nodes`. You implied that GPU nodes should be available to Scale so I'm wondering if the problem is that when I built my DC/OS cluster I added GPU support by adding the following lines to my `config.yaml`:
```
enable_gpu_isolation: 'true'
gpus_are_scarce: 'true'
```
Do you think Scale will be able to see my GPU nodes if I reinstall my DC/OS cluster with `gpus_are_scarce: 'false'`?

**Comment by gisjedi** [comment]
`gpus_are_scarce: 'false'` is definitely a requirement for Scale to execute GPU algorithms on that node. Without this setting, Mesos will not give resource offers to Scale from nodes that contain GPUs. Regardless of this, you should have seen the nodes from the Nodes page in Scale - it is just a Scale view of the Mesos private agents. Are those nodes displaying as expected in the DCOS Nodes UI (`https://my-dcos-admin.com/#/nodes`)?

**Comment by nevasway** [comment]
I'll go ahead and change the `gpus_are_scarce` parameter and rebuild my cluster.  One thing to note is that I have Scale v5.4.0 running on DCOS v 1.11.1. I heard that the *next* version of Scale will be compatible with DCOS v1.11.

I have 6 Agent Nodes, 1 is Public (no GPUs), 2 Private Nodes have GPUs. The remaining 3 Private Nodes are the ones that show up on Scale's web interface. The attached picture shows the web interfaces for DC/OS and Scale side by side.
<img width="966" alt="screen shot 2018-06-01 at 11 55 31 am" src="https://user-images.githubusercontent.com/6116276/40850588-0b90fe64-6593-11e8-9f00-f3351dc42a55.png">

**Comment by dfaller** [comment]
Scale recognizes a Mesos private agent once it has first received resources for that agent from Mesos, so the `gpus_are_scarce` parameter is affecting those two private nodes. Switching it to false will allow Scale to receive resources from those nodes and it will therefore display them.

I'm not aware of anything in the next version of Scale specifically geared towards support of DC/OS 1.11. Scale 5.4.0 should work just fine with DC/OS 1.11. If you have seen any issues with Scale 5.4.0 and DC/OS 1.11, please let us know.

**Comment by nevasway** [comment]
I'm following up to report that I successfully rebuilt my DC/OS cluster with `gpus_are_scarce: 'false'` and my new deployment of Scale can now see all my agent nodes with GPUs. Thank you for your help.

**Comment by dfaller** [comment]
No problem. Let us know if you need anything else.

**Comment by gisjedi** [comment]
When we fully enable Scale to consume GPU offers we should consider the scarcity concerns in a manner similar to Marathon: https://mesosphere.github.io/marathon/docs/preferential-gpu-scheduling.html

This should be exposed as an environment on the Scale container so that the scheduler can make a proper determination when launching on how to schedule when GPU offers are encountered.

**Comment by gisjedi** [comment]
The following steps should be taken to test GPU support:

- Update Scale to accept GPU resource offers here: https://github.com/ngageoint/scale/blob/1f46d70390273140a60c6a7cb791509131cd7c18/scale/scheduler/management/commands/scale_scheduler.py#L85 
- Apply configuration to Mesos GPU agents to ensure GPUs are available: https://github.com/ngageoint/scale/wiki/Adding-NVIDIA-CUDA-support-to-your-Mesos-Docker-Containerizer
 
Once that change has been made, GPU offers should be received by Scale. I’m not 100% sure that it will work because Scale uses the Docker containerizer which does not support GPU isolation (Mesos Containerizer does), but it’s worth a shot. All that will be needed then is a Scale job that requires the `gpu` resource.
