### ISSUE TITLE
Capture and report failure to launch Docker image

### ISSUE THREAD

**Issue by dev-geo** [ngageoint/scale#122]
When a docker image fails to run on a node, "Unknown system error" is reported. Please make this a SYSTEM error with text such as "Failed to run docker image".

**Comment by dfaller** [comment]
This can be determined by receiving a task failure message before a task running message.

We should create three new errors:
1. SYSTEM Error: Command line Mesos task failed to launch
2. SYSTEM Error: Docker Mesos task failed to launch
3. ALGORITHM Error: General algorithm failure where no exit code mapping was provided

In description for error 3, include a high level explanation of defining exit code mappings for the algorithm to get better error reporting.

Add method to the base task for being a 'catch-all' in case the specific task logic (pre-task, job-task, post-task) does not come up with an error. Each specific task should call this base logic if they can't come up with an error (instead of defaulting to unknown). The base task method should check if a failure message (other than lost) occurred before a task running message and if so, return new error 1 (is task uses_docker is False) or new error 2 (if task uses_docker is True).

The job task should use new error 3 if a valid failed exit code is provided, but there is no exit mapping for it.

**Comment by dfaller** [comment]
Merged into master
