### ISSUE TITLE
Job Type Names fields

### ISSUE THREAD

**Issue by ericsvendsen-mil** [ngageoint/scale#1503]
If possible I need `is_active` and `is_paused` added to the results for the job type names endpoint.

**Comment by JohnPTobe** [comment]
What is the motivation behind this? So you can hide paused or deprecated job types?  Since those flags can differ for multiple versions of a job type for a given name, what value should I use? The latest version? True for active if any is active? False for paused if none of them is paused?  Currently you can pass is_active=true to only get names where at least one version is active. I could add something similar for is_paused. These values are given in the job type versions endpoint which I think you would have to call for each name returned in the job type names endpoint anyway.

**Comment by JohnPTobe** [comment]
After discussion with Eric and Chris, I'm moving the current job-types endpoint to job-type-names and changing the job-types endpoint to return all job types with the same details as the job-type-versions endpoint.  The new job-types endpoint will use the same parameters as job-type-names for filtering.
