### ISSUE TITLE
Convert configs to v6

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale#1551]
Add code in the database updater to update all configs stored in the database to v6 versions.

**Comment by emimaesmith** [comment]
Existing Scale configuration/definitions with versions. Configurations/definitions in bold will need to be converted in order to run Scale 7.0.

batch:
- batch/configuration/json/configuration_v6
- batch/definition/json/definition_v6

data:
- **data/data/json/data_v1**
- data/data/json/data_v6
- data/filter/json/filter_v6
- data/interface/json/interface_v6

ingest: 
- **ingest/scan/configuration/json/configuration_1_0**
- ingest/scan/configuration/json/configuration_v6
- **ingest/strike/configuration/json/configuration_1_0**
- **ingest/strike/configuration/json/configuration_2_0**
- ingest/strike/configuration/json/configuration_v6

job: 
- **job/configuration/json/job_config_2_0**
- job/configuration/json/job_config_v6
- job/execution/configuration/json/exe_config
- job/execution/configuration/json/exe_config_1_0
- job/execution/configuration/json/exe_config_1_1

recipe:
- recipe/configuration/json/recipe_config_v6
- **recipe/definition/json/definition_v1**
- recipe/definition/json/definition_v6
- recipe/diff/json/diff_v6
- recipe/diff/json/forced_nodes_v6
- recipe/instance/json/recipe_v6

storage: 
- storage/configuration/json/workspace_config_v6

**Comment by emimaesmith** [comment]
We have methods to convert configurations on the fly. Do we still need a mass database update to convert each old configuration?

**Comment by JohnPTobe** [comment]
We don’t have conversions for everything.  A lot were removed. I had to add support for v2 job configs back recently. If there are conversions then I think we’re fine.

**Comment by emimaesmith** [comment]
Agreed. Closing this as resolved.
