### ISSUE TITLE
Multiple POSTSs of a Recipe Type definition results in duplicates

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1636]
When submitting a Recipe Type, if the user accidentally executes multiple POSTs of the definition, duplicate recipe types will be created and de-conflicted by a GUID value. This behavior is highly undesirable as there is no supported way to remove Recipe Types and now duplicate types exist with no way to clean out.

**Comment by emimaesmith** [comment]
After discussion we decided if a recipe type is discovered to exist already, an error message will be returned to patch the existing type and no new recipe type will be re-created. We decided not to simply edit the existing type in order to prevent possible unwanted updates since the unique identifier of recipe types is derived from the recipe type title.

Closed via https://github.com/ngageoint/scale/pull/1643
