### ISSUE TITLE
Paged Results Return 403 Forbidden

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale#1654]
Attempting to retrieve paged results beyond the first page for rest api endpoints results in 403 forbidden responses (authentication credentials were not provided).

**Comment by mheppner** [comment]
This is mostly resolved, at least off site.

HAProxy seemed to not be respecting `HAPROXY_0_BACKEND_REDIRECT_HTTP_TO_HTTPS`. Using `HAPROXY_0_REDIRECT_TO_HTTPS` appears to be giving the correct 301 redirect.

The way Django builds absolute URI's is by looking at a few headers provided by the WSGI server. In DRF, the pagination links in the browseable API were built using incorrect headers, sending the user to a non-https version. Since `SESSION_COOKIE_SECURE` is true, the user's session is invalid for non-https. Changing the HAProxy label at least allows those links to work as expected, but there are still some underlying issues.

[`SECURE_PROXY_SSL_HEADER`](https://docs.djangoproject.com/en/1.11/ref/settings/#secure-proxy-ssl-header) needs to be set, which allows Django to interpret whether or not the request was made from HTTPS based on the forward proxy headers. However, the WSGI server is receiving `HTTP_X_FORWARDED_PROTO` as `http`, so the value is being lost in one of the forwarding proxies. This is causing the DRF pagination links to be built using the non-https version, which is at least mitigated by the redirect mentioned above.
