### ISSUE TITLE
Media Types Shouldn't Be Required to Match

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale#1668]
Make media types optional when creating jobs and recipes. Validation should be updated to warn about mismatching job types, but not error out. The UI has been updated to ignore mismatches/missing media types, so now need to ensure the API will also not throw validation errors.

**Comment by mheppner** [comment]
From what I can tell, `/v6/recipe-types/validation/` and `/v6/job-types/validation/` both support leaving `mediaTypes`/`media_types` either set to an empty array, or completely leaving them out of the request. They do error if set to `null`. I'll verify this is the expected behavior with Eric or Rachel.

**Comment by JohnPTobe** [comment]
/v6/recipe-types/validation/ will warn if media types are mismatched but won't error.

**Comment by mheppner** [comment]
Confirmed with Eric that this is no longer an issue.
