### ISSUE TITLE
Upgrade Django

### ISSUE THREAD

**Issue by wardcr** [ngageoint/scale#168]
After DRF was upgraded, we still need to update Django itself. Initial research was provided by Trevor in issue #28 and the remaining items from there include:
- There are new TestCase enhancements to speed them up by using setUpTestData() instead of setUp(). Code changes needed but existing code will continue to work.
- Check use of Model._meta in case there are deprecated calls.
- GeoJSON native queries in database queries postgis extension is automatically created by migrate so a postgis template database is no longer needed.
- Look into data migrations
- manage.py tests --parallel
- Added the json() method to test client responses to give access to the response body as JSON.
- Update custom commands to use the new argparse system.

**Comment by gisjedi** [comment]
Things to review: 

- Use of `check --deploy` on production settings
- UUIDField and DurationField for storing UUIDs
- Investigate using setUpTestData for class wide data initialization. May be faster than setUp for TestCase level data initialization.
- Use of data migrations instead of fixtures

Deprecation Compliance:

- Address URL patterns change first deprecated in 1.8 (https://docs.djangoproject.com/en/1.10/releases/1.8/#django-conf-urls-patterns)
- Eliminate string reference to callable view in favor of actual callable
- Update `MIDDLEWARE_CLASSES` to `MIDDLEWARE` in settings.py file. (https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-middleware)
- Update software dependencies to indicate PostGres 9.2 as a minimum supported version in line with Django 1.10 requirement.

**Comment by gisjedi** [comment]
Issues discovered:

- 'django.utils.log.NullHandler' was an alias, replaced with 'logging.NullHandler'
- Updating to use JSONField is problematic as we as using the PostGres 9.3 JSON string field. If we use Django native PostGres support we will enforce a PostGres 9.4 upgrade and the JSONB field type. djorm-ext-pgjson does not support Django 1.10, so we will need to switch to a supported library (django-pgjson is one such that does not enforce an upgrade to JSONB type field)
- Remove all use of url patterns in favor of simple url tuples
