### ISSUE TITLE
Fix Error Category Colors on Overview

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#182]
On the overview page, the error category colors can change depending on which error categories are present. This can be very confusing to the user. Please set each error category to a permanent color.

Note: This seems to affect the colors in the 'wheel' around the percentage. The error category labels appear to be correct.

**Comment by dfaller** [comment]
Also please change the colors. The green used is confusing in the context of an error color. It would probably be a good idea to change the orange as well. We want the category colors to have good contrast, but not be confused with the green/yellow/red spectrum that is used to indicate the job type health.

**Comment by wardcr** [comment]
This is a good site for picking colors in data visualizations: http://colorbrewer2.org/

I suggest selecting the red column under "Single hue" for this use case, which will give you 3 differentiated shades of red.

**Comment by wardcr** [comment]
I was thinking about this more and I'm getting the feeling we're trying to cram too much into this UI element. How about this design...

- Assign the 3 shades of red for the error categories.
- Color the grid cell background with the most appropriate shade of red based on the errors that are happening. So either we use highest percentage or highest severity.
- Show the breakdown of the errors with colored boxes in the tool-tips, which also acts as a legend and reinforces the scheme. Then we don't need the separate legend in the upper-right.
- Slide the icons up a bit within the cell and move the running count to the bottom center so that the content isn't overlapping and remove the spinners. The counts already imply that things are running and is a bit less distracting than all the spinners.

I think that simplifies the UI, while hopefully still conveying the same general information.

**Comment by ericsvendsen-mil** [comment]
@wardcr I like the idea of simplifying this, and getting rid of the spinners is definitely a good idea since they only spin in Chrome anyway.

I set things up as you suggested - right now the background color is selected based on the type of error that has the highest count, but like you said that's something we can change based on feedback.  I don't know if I like limiting the background for failed job types to 1 color, since that could give a false impression at a glance regarding what's going on, but I think this is a step in the right direction.

What if we partition the cell background color based on failure types?  Since they're all shades of red now, it might work.  Thoughts?

**Comment by wardcr** [comment]
Yeah that might be okay. I think we'd have to try it before I could form a final opinion. It would be nice to show the extra information as long as it doesn't become too busy and hurt the readability. We might be able to make the text a bit more bold or have a slight drop shadow to help alleviate that.

So perhaps try treating each cell as a vertical meter, where it goes lighter to darker from top to bottom?

**Comment by ericsvendsen-mil** [comment]
Changed the cell background to a gradient, which changes based on the type(s) of error(s) reported for that job type.

**Comment by ericsvendsen-mil** [comment]
This change was merged in a while ago.
