### ISSUE TITLE
Import errors when null max_scheduled or author_url

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#190]
The import REST API now errors when max_scheduled or author_url is not provided for a job type. This may be a result of the DRF update.

**Comment by wardcr** [comment]
I tried to create a unit test that does a job type import with only the minimum required fields and it worked, so I am currently unable to reproduce the issue.

**Comment by wardcr** [comment]
Okay after further troubleshooting, I found out the root cause. I was testing this case by omitting the optional fields, which does work. However, if you send an optional integer field with a null value or an optional string field with an empty string value, then it gets rejected. This comes up when a user copies/pastes the output of say the job-type details service as a starting point for the import because that's how those fields get rendered when they are not filled in. We can see if there is an easy way to relax the validation so that these cases do not produce an error, but in the short term it's easy to workaround by just deleting the fields from the input.
