### ISSUE TITLE
Update Django and django-rest-framework

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#28]
Update the versions of Django and django-rest-framework used by Scale. This will require some investigation into the Django changes and possibly making appropriate updates to Scale.

**Comment by tclarke** [comment]
Initial feelings on what we need to fix or pay attention to:

* There are new TestCase enhancements to speed them up by using setUpTestData() instead of setUp(). Code changes needed but existing code will continue to work.
* Check use of Model._meta in case there are deprecated calls.
* GeoJSON native queries in database queries
* postgis extension is automatically created by migrate so a postgis template database is no longer needed.
* Look into data migrations
* manage.py tests --parallel
* Added the json() method to test client responses to give access to the response body as JSON.
* pagination.PaginationSerializer -> pagination.BasePagination
* rest_framework.fields.WritableField -> rest_framework.fields.Field
* serializers.RelatedField() needs read_only=True

**Comment by wardcr** [comment]
DRF upgrade work is included in PR #134

**Comment by dfaller** [comment]
Merged into master
