### ISSUE TITLE
Allow passing additional parameters to the docker container

### ISSUE THREAD

**Issue by dyerz** [ngageoint/scale#33]
In order to support changing network layouts, I need to be able to pass the "add_host" parameter to a docker depending on certain job types. I have checked in a possible solution to my fork. [Commit](https://github.com/dyerz/scale/commit/99e7cbd285135770941f3064ab4224d957d19152)

**Comment by tclarke** [comment]
Make a pull request with this commit and we'll review it.

**Comment by dfaller** [comment]
The Docker parameters should not be in the job type interface since that should be Docker and environment agnostic and just focus on the algorithm itself. We should do a Docker parameters JSON field that gets populated in job_type and passed to job. The field in job can be used in the execution tasks to add parameters when creating a Docker Mesos task.

Adam, if you can wait until next week, I can add the Docker param fields next week when dealing with other model changes to job_type and job for the supersede functionality. It'll be easier without database migration conflicts.

**Comment by dfaller** [comment]
The Docker parameter functionality is going to be removed due to security concerns. Every current known use case for using Docker parameters has been implemented into Scale.
