### ISSUE TITLE
"Vagrant up" scale UI is not accessible

### ISSUE THREAD

**Issue by mchendricks1** [ngageoint/scale#39]
There are three URLs I've noticed in the README.md file with regards to running this from a vagrant startup sequence.

http://master
http://master:8081
http://master:5050

The last one (http://master:5050) appears to connect fine through the host browser (MacOS 10.11). However, the other two URLs fail to connect. It says "Firefox failed to connect to server".

**Comment by tclarke** [comment]
If the first two are not connecting it's likely because scale didn't properly come up. The first URL connects to the scale-web-static instance in docker which serves the static web content and proxies to the scale-web instance. The second is part of the examples and is another docker container with a basic file upload capability. Do a `docker ps` on the master and see if the docker containers are running. If not, the provisioning didn't complete properly. You can try to `vagrant provision` to run through the process again. If they are running then there might be some network configuration issue on your host preventing you from connecting.
