### ISSUE TITLE
Node hostnames and job history in EC2 environment

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#40]
Where (virtual?) nodes may automatically spinup/join/shutdown/destroy on a regular basis the concept of active/inactive offline/online may not make as much sense.  Should we abandon hostnames for a GUI name or just "pass the buck" through to mesos?

**Comment by tclarke** [comment]
Perhaps a system wide config option for transient slaves which will only show them as unavailable for a certain period of time then they become inactive unless seen again.
Another option would be to allow a slave to explicitly de-register itself when it cleanly shuts down.
A third option (perhaps linked with the others) would be an option to specify a node ID when a slave starts up so that moving a slave to another VM host can use the same node ID

**Comment by dfaller** [comment]
This is OBE.
