### ISSUE TITLE
Exception in new scheduler

### ISSUE THREAD

**Issue by dyerz** [ngageoint/scale#42]
The following exception is occurring often with the latest changes to the scheduler.

```
ERROR [scheduler.scale_scheduler(293)] Error handling status update for job execution: #
Traceback (most recent call last):
   File "/opt/scale/scheduler/scale_scheduler.py", line 265 in statusUpdate
      task_dir = get_slave_task_directory(hostname, port, task_id)
   File "/opt/scale/mesos_api/api.py", line 241 in get_slave_task_directory
      raise MesosError('Task not found: %s' % task_id)
```

**Comment by dfaller** [comment]
Yeah, this occurs when Scale queries Mesos to find the logs for a task and Mesos doesn't seem to have the task.

I have a fix in a branch that wraps the logs piece so that if it fails, the rest of the status update succeeds (the job execution then does not have the missing logs).

I think this might be occurring on TASK_STAGING updates. Mesos might (or probably) not yet have a task sandbox yet when TASK_STAGING is sent. At any rate, we don't need the logs for TASK_STAGING or TASK_STARTING updates (we ignore those statuses). I will include another fix that only attempts to grab the logs for exactly the statuses that need it.

Long term the log retrieval will be removed from the scheduler entirely.
