### ISSUE TITLE
Requeue Job API Broken

### ISSUE THREAD

**Issue by wong-j** [ngageoint/scale#532]
API documentation for requeue job seems to have wrong example of JSON to submit to requeue jobs.

Submitting JSON to the API returns a 404 error

Requeue doesn't work when requeuing many jobs (multiple days worth) through API or with Requeue All button

Requeue All button grabs more than what is selected

**Comment by wardcr** [comment]
The problem with requeuing many jobs is already covered by issue #183

**Comment by wardcr** [comment]
I fixed the HTML POST form to start out with valid example fields, added a valid example to the REST API docs, and changed the view to return a success response when no jobs match the query to avoid the 404 error confusion. Since handling many jobs is covered in the other issue, that just leaves the requeue all button problem. If you think there is still a separate UI bug there, then please open a separate issue for just that with more details on what's happening.
