### ISSUE TITLE
Investigate use of vault

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#543]
Investigate use of vault for sending secrets to Scale tasks.

**Comment by mikenholt** [comment]
# Vault Notes
## Core concepts
### `secrets`
These are the tokens, user/pass, keys that you want to secure. Vault takes these and stores them in a `backend`.  The backend storage mechanism never sees the unencrypted value and doesn't have the means necessary to decrypt it without Vault.
- Write ex.: `vault write secret/hello value=world excited=yes`
- Read ex: `vault read -format=json secret/hello`
- Delete ex: `vault delete secret/hello`

### `secret backends`
Secret backends are the components in Vault which store and generate secrets.  

Some secret backends, such as `generic`, simply store and read secrets verbatim. Other secret backends, such as `aws`, create dynamic secrets: secrets that are made on demand.

Secret backends are part of the mount system in Vault. They behave very similarly to a virtual filesystem: any read/write/delete is sent to the secret backend, and the secret backend can choose to react to that operation however it sees fit.

- Types of backends as of *October 2016*:
    - `aws`
    - `cassandra`
    - `generic`
    - `mongodb`
    - `mssql`
    - `mysql`
    - `pki`
    - `postgresql`
    - `rabbitmq`
    - `ssh`
    - `cubbyhole`


  - `vault mount *generic*` - This mounts a new secret backend. Multiple secret backends of the same type can be mounted at the same time by specifying different mount points. By default, secret backends are mounted to the same path as their name. This is what you want most of the time.

  - `vault unmount *generic*` - This unmounts an existing secret backend. When a secret backend is unmounted, all of its secrets are revoked (if they support it), and all of the data stored for that backend in the physical storage layer is deleted.

  - `vault remount *generic*` - This moves the mount point for an existing secret backend. This revokes all secrets, since secret leases are tied to the path they were created at. The data stored for the backend won't be deleted.


### `auth backends`    
Auth backends are the components in Vault that perform authentication and are responsible for assigning identity and a set of policies to a user.

Having multiple auth backends enables you to use an auth backend that makes the sense for your use case of Vault and your organization.

For example, on developer machines, the GitHub auth backend is easiest to use. But for servers the AppRole backend is the recommended choice.

When enabled, `auth backends` are similar to `secret backends`: they are mounted within the Vault mount table and can be accessed and configured using the standard read/write API. The only difference is that all auth backends are mounted underneath the `auth/` prefix.

- Types of backends as of *October 2016*:
    - `AppRole`
    - `aws-ec2`
    - `github`
    - `ldap`
    - `userpass`
    - `cert`
    - `token` -  The token backend is the only auth backend that is built-in and automatically available at `/auth/token` as well as with first-class built-in CLI methods such as `vault token-create`.


- `vault auth-enable *github*` - Auth backends are mounted, just like `secret backends`, except auth backends are always prefixed with `auth/`. So the GitHub backend we just mounted can be accessed at `auth/github`.
- `vault write auth/github/config organization=ngageoint`
- `vault auth-disable github`
- `vault token-revoke -mode=path auth/github`



# System Notes
- With [vault-gatekeeper-mesos](https://github.com/ChannelMeter/vault-gatekeeper-mesos), vault will need a 1:1 policy:mesos task name JSON file
  - This config file would need to be reloaded after any change (new algorithm added, new database, etc.).
- nodes can authenticate against vault via certs, approle, or user/pass
- the general community approach to using vault with docker is to have a shell script in the docker image that is able to get secrets. 
- passing secrets as environment variable is another option. 
- possible for vault to generate auth access on-the-fly and revoke often 
- possible to have each algorithms have its own token/cubbyhole (high security)
