### ISSUE TITLE
S3 Strike gets stuck on bad messages

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#616]
If the S3 Strike receives a malformed message on the SQS queue, it does not delete it. This results in the Strike becoming stuck at that point until the message is removed out of band.

**Comment by gisjedi** [comment]
Verified that this is not an actual bug, but is an intended behavior. The invalid message will cause an error in the Strike, but is handled and logged. Due to the VisibilityTimeout default of 120 seconds, the bad message will, at most, only appear every 2 minutes while still allowing other messages to be processed. Manual intervention will be required to remove the message, but it is desirable to heighten the error visibility instead of silently throwing away unrecognized messages.
