### ISSUE TITLE
Sanitize API requests based on form field input for optional fields.

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#641]
There are a number of API requests that send empty or whitespace filled values from UI forms. Strike, Job Type and Workspace forms are the most common offenders. Good examples are the credential fields for AWS access keys and `host_path` in the workspace configuration. The ultimate goal being that any optional field should not be sent as an empty string, but instead be entirely omitted from the request.

**Comment by gisjedi** [comment]
@wardcr  Do you have any input on this or good suggestions on how we could better take advantage of the existing JSON schema to simplify this on the UI side?

**Comment by dfaller** [comment]
As part of this issue, the AWS credential check in the REST API should raise an exception if the provided credentials are blank (or whitespace only) strings.

**Comment by wardcr** [comment]
I typically follow the robustness principle (be conservative in what you send, be liberal in what you accept) as much as possible. Therefore, I tend to treat empty string or nulls as the same for caller convenience since reading an empty value from a form in the UI will result in an empty string by default. JSON schema does support things like min-length and regex patterns for validation, but I wouldn't recommend rejecting empty strings unless nulls/omitted values are also rejected. I do agree that the UI should not be sending strings of white space though and I'm not sure how that might happen.

**Comment by dfaller** [comment]
I agree with the principle, but I wonder if it might be more confusing for the user if they are attempting to submit (blank) access keys and role-based auth is automatically used instead.

**Comment by wardcr** [comment]
If that's the case, then the UI could maybe be designed to force an explicit choice of role-based or credential based auth before presenting the extra form fields.
