### ISSUE TITLE
Batch creator does not skip already re-processed recipes

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#654]
If the batch creator fails and runs again, it will re-process recipes it had previously re-processed instead of skipping them as it should.

Also it would be helpful to log a completion percentage so the job's progress can be seen in the logs.

**Comment by wardcr** [comment]
I might need a bit more information to track this down because I made an effort to cover that case explicitly, so perhaps I'm missing something about how this is supposed to work?

The query that is used to get the recipes that need to be updated has a check to make sure the recipe is not already superseded:
https://github.com/ngageoint/scale/blob/master/scale/batch/models.py#L181

And then later on, once a recipe is superseded it also creates a corresponding BatchRecipe at the end of the same transaction. There is a check to make sure the recipe is not re-submitted when that model already exists:
https://github.com/ngageoint/scale/blob/master/scale/batch/models.py#L217

And there is a unit test that was attempting to cover this case as well:
https://github.com/ngageoint/scale/blob/master/scale/batch/test/test_models.py#L190

**Comment by dfaller** [comment]
I have verified that this bug does indeed exist. I think the problem is as follows:

Batch creator runs and superseded recipe A with recipe B.
Batch creator fails/times out.
Batch creator runs again.
Batch creator detects BOTH recipe A and recipe B as candidates for its re-processing.
Batch creator skips recipe A due to `if BatchRecipe.objects.filter(batch=batch, superseded_recipe=old_recipe).exists(): return`
Batch creator supersedes recipe B with recipe C since recipe B was not previously superseded (it was instead the "new" recipe, not the old).

So recipe A gets superseded twice, first as B and then B is replaced by C.
I think the check for old recipes has to check both of the batch_recipe fields relating to recipes, i.e. skip any recipe that has any relation to the current batch already.

**Comment by dfaller** [comment]
This issue no longer exists due to the transition of recipe reprocessing to the messaging backend: #1029
