### ISSUE TITLE
vagrantfile fails on macOS Sierra

### ISSUE THREAD

**Issue by stephenHartzell** [ngageoint/scale#702]
In particular, Ansible seems to be what's failing. Here's the error I get:

```
TASK [common : docker service] *************************************************
task path: /Users/shartzell/projects/scale-master/ansible/roles/common/tasks/main.yml:69
fatal: [scale-master]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}
	to retry, use: --limit @/Users/shartzell/projects/scale-master/ansible/vagrant.retry

PLAY RECAP *********************************************************************
scale-master               : ok=14   changed=2    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I don't know much about Ansible, so I'm not sure what it's trying to do. If it's trying to run the "systemctl ..." command then that would explain the error as MacOS doesn't have systemctl. Does this only work on Linux? I tried to run this on Ubuntu, but ran into separate issues.

**Comment by dfaller** [comment]
Yeah, we are aware of issues with the ansible scripts. We are planning on phasing them out due to the difficulty and complexity of getting them to work consistently.

The recommended path for trying out Scale is to use our QuickStart guide which involves installing Mesosphere DC/OS: [Quickstart](http://ngageoint.github.io/scale/quickstart.html)
