### ISSUE TITLE
Batch UI Issues

### ISSUE THREAD

**Issue by dickmanp** [ngageoint/scale#791]
Found the following issues when using the new Batch UI.

1.  Batch Creation.
- The date range should allow times to be specified.  Specifying the same date for the start and end causes nothing to be processed (both times default to 0).
- Job selection should only include jobs in the selected recipe.
- If you select a job, nothing seems to process.  I could only get something to work when using the "all jobs" option.
- Priority setting seems to get sent as a string and throws a conversion error.

2.  Batch Details.
- Would like to see the requested date range (start, end, type)
- Would like to have links to recipes, jobs, products, ... associated with the batch
- All of the counts are currently showing 0, even when reprocessing is successful

3. Batch List.
- Failure rates show NaN%
- Is it possible to show a status of "Completed" in addition to Submitted and Created?

**Comment by ericsvendsen-mil** [comment]
Progress on this issue, with some **comments**:

1.  Batch Creation.
- ~~The date range should allow times to be specified.  Specifying the same date for the start and end causes nothing to be processed (both times default to 0).~~
- ~~Job selection should only include jobs in the selected recipe.~~
- ~~If you select a job, nothing seems to process.  I could only get something to work when using the "all jobs" option.~~ - **not sure what might have been causing this, but once the jobs dropdown was tied to the recipe type, I was able to process a batch successfully when selecting a job.**
- ~~Priority setting seems to get sent as a string and throws a conversion error.~~

2.  Batch Details.
- Would like to see the requested date range (start, end, type)
- Would like to have links to recipes, jobs, products, ... associated with the batch
- ~~All of the counts are currently showing 0, even when reprocessing is successful~~ **this was an API issue that has been fixed in dev**

3. Batch List.
- ~~Failure rates show NaN%~~
- ~~Is it possible to show a status of "Completed" in addition to Submitted and Created?~~ **changed failure rate to job creation rate to let the user know what percentage of jobs the batch has created successfully**

**Comment by dickmanp** [comment]
On the batch list screen, I would be a lot more interested in the completion percentage of the batch than the percentage that was created.  As a user, I want to know when my batch is finished not started.

**Comment by ericsvendsen-mil** [comment]
Right - I agree with you on that.  It's something that I believe @dfaller has in the pipeline, as that is currently not supported by the API.  So until that's done we'll just go with this.

**Comment by dfaller** [comment]
Yeah, I'll create a new issue for actual job completion/failure counts when I get around to doing some re-processing work.

**Comment by ericsvendsen-mil** [comment]
Ok. Closing this issue then since I just merged the PR.
