### ISSUE TITLE
DC/OS create scale service failed

### ISSUE THREAD

**Issue by comxtohr** [ngageoint/scale#827]
Hi I'm trying to deploy scale(version 4.4.1) on DC/OS following quickstart tutorial (http://ngageoint.github.io/scale/quickstart.html).

After I created `marathon-lb` and `elasticsearch`(has scaled to 4 running tasks) service, I tried to create `scale` service. However, the status of `scale-db` task stucked at "waiting".

So I destroyed `scale` and `scale-db` service, created a `scale-db` service(using `mdillon/postgis:9.5`) manually, and tried to recreate a `scale` service. This time it created `scale`, `scale-logstash` and `scale-webserver` service. 

`scale` and `scale-logstash` service created and ran successfully but status of `scale-webserver` stucked at "waiting". 

I've tried to deploy scale both on DC/OS 1.8.8 (with Docker 1.10) and DC/OS 1.9 (with Docker 1.10 Docker 1.13)and scale deployment on all these environments failed.

Could anybody help me out? Thanks a lot!

**Comment by gisjedi** [comment]
@comxtohr So, I'm going to take a quick stab and guess you are trying this with DCOS Vagrant. If that is not the case, please let me know.

I'm assuming the waiting is occurring because insufficient resources are available. If you bump up the number of nodes or the sizes of them you should be able to move forward.

The following VagrantConfig.yaml example should get you running: https://github.com/ngageoint/scale/issues/598#issuecomment-264199762

**Comment by comxtohr** [comment]
@gisjedi DC/OS is deployed in VMware vSphere via Terraform. It has 3 masters(4CPU, 32G RAM, 120G Disk), 3 private agents(2CPU, 16G RAM, 60G Disk), 3 public agents(2CPU, 16G RAM, 60G Disk)

**Comment by gisjedi** [comment]
You definitely aren't starved in the memory department, but the CPUs are going to be inadequete. Our recommendations for a minimal cluster outlined here:

https://github.com/dcos/examples/tree/master/scale/1.8#prerequisites

That will get you up and running with Scale, but you'll still need to ensure you have enough beyond that for the jobs you intend to run.

**Comment by comxtohr** [comment]
@gisjedi  After I changed cpu number of the agent, problem solved. Thanks a lot!
