### ISSUE TITLE
Fix logging fields in ElasticSearch

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#878]
When we upgraded Docker, it appears that the same logging fields do not make it into ElasticSearch, in particular the stdout/stderr information appears to be lost. This is probably due to the Docker syslog output changing slightly and then not being parsed correctly by our logstash configuration. Investigate and correct.

**Comment by gisjedi** [comment]
I've identified this as an issue with Docker engine. This has been broken between 1.12.6 and 17.03 of Docker. I'm working to identify where exactly this issue was introduced in order to file an issue with them.

Reproduction steps:

```bash
docker run -it -p 8000:8000 --rm logstash:2.4-alpine -e 'input { syslog { port => 8000 } } output { stdout { codec => rubydebug } }'
# Need to remove tty as that redirects all output to stdout
docker run --rm --log-driver syslog --log-opt syslog-format=rfc3164 --log-opt syslog-address=tcp://localhost:8000 python:2-alpine python -c 'from __future__ import print_function; import sys; print("stderr", file=sys.stderr); print("stdout", file=sys.stdout)'
```

On 4.7.3-coreos-r3 with Docker 1.12.6 I get severity:3 and severity_label=Error for stderr and severity:6 and severity_label=Informational for stdout
On CentOS 7 kernel vs 3.10.0-514.16.1.el7.x86_64 with Docker 1.12.6 from centos repos I get severity:3 and severity_label=Error for stderr and severity:6 and severity_label=Informational for stdout
On CentOS 7 kernel vs 3.10.0-514.16.1.el7.x86_64 with Docker 17.06.0-ce from docker repo I get severity:6 and severity_label=Informational for BOTH stderr and stdout

**Comment by gisjedi** [comment]
Here is the relevant Moby issue: https://github.com/moby/moby/issues/33834. PR is in: https://github.com/moby/moby/pull/33832. Doesn't appear to have made it in a Docker release yet though... https://github.com/docker/docker-ce/pull/95

**Comment by gisjedi** [comment]
Our options are to use either Docker 12 / 13 or wait until 17 receives a patch release for this.

**Comment by dfaller** [comment]
All right, let's wait for the patch. No sense going back to earlier Docker versions for this.

**Comment by dfaller** [comment]
Closing...
