### ISSUE TITLE
DC/OS create scale service failed on scale-logstash 

### ISSUE THREAD

**Issue by ballazar** [ngageoint/scale#940]
This issue is very similar to https://github.com/ngageoint/scale/issues/827

I'm trying to deploy scale on DC/OS following quickstart tutorial (http://ngageoint.github.io/scale/quickstart.html).  I'm running DC/OS on AWS with 3 masters(4CPU, 15G RAM, 2x40 G Disk), 5 private agents(4CPU, 15G RAM, 2x40 G Disk), 1 public agent (1CPU, 3.75G RAM, 4G Disk) per the DO/OS setup configuration page.

I created marathon-lb and elasticsearch(has scaled to 4 running tasks) service, I tried to create scale service. However, the status of scale-logstash task stucked at "waiting".

scale, scale-db, and scale-rabbitmq services were created and ran successfully but status of scale-logstash stucked at "waiting".

I've tried to increase the CPU for scale-logstash like the previous post, but got this error message:
There is an error with your configuration
     healthChecks: Marathon protocols `HTTP` deprecated. Please use `MESOS_HTTP instead

Could anybody help out a newbie? Thanks a lot!

**Comment by gisjedi** [comment]
This is the first time I've seen an issue deploying Scale into a cluster of that size. Any time a task is stuck in `waiting` state it is due to insufficient cluster resource offers. This can be any type of resource: disk, cpu, mem, ports, gpu, etc. In the case of the logstash container, this should be 0.5 cpu, 1024 mem and 9229 host port. In a new cluster of that size, you should haven't any trouble satisfying those resource needs.

The only real way to identify this authoritatively is to see what resource offers are being given to Marathon and what isn't being satisfied. This can be done by running the following command on the leading DCOS master (or just do this on all 3):

```
sudo journalctl -f -u dcos-marathon
```

You should be able to see the resource offers being made and Marathon making a determination on whether they meet the `scale-logstash` requirements or not. This should indicate what resource you are lacking.

**Comment by ballazar** [comment]
I tried to see the resource offers being given to Marathon, and just can't seem to pick out the needle in the haystack in all the journal entries.  

Looks like the issue is actually with the DC/OS version I've been using.  Previously when I created the cluster with DC/OS, somehow the template put in DC/OS version 1.10 beta.  I knew this might have been an issue since Stack seems to require version 1.9.  When i recreated the DC/OS stack again an hr ago, the template put in version 1.9.1, and installing the Scale service was a breeze.
